# Create deployment: 2 hello replica
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
spec:
  selector:
    matchLabels:
      app: hello
  replicas: 2
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: paulbouwer/hello-kubernetes:1
        ports:
        - containerPort: 8080
#      affinity:
#        nodeAffinity:
#          requiredDuringSchedulingIgnoredDuringExecution:
#            nodeSelectorTerms:
#            - matchExpressions:
#              - key: ingress-ready
#                operator: DoesNotExist
---
apiVersion: v1
kind: Service
metadata:
  name: hello
spec:
  ports:
  - name: http
    targetPort: 8080
    port: 8080
  selector:
    app: hello
### To debug metallb install without ingress-nginx
#  loadBalancerClass: metallb.universe.tf/metallb
#  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-ingress
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    # IP White list
    # nginx.ingress.kubernetes.io/whitelist-source-range: x.x.x.x/32,y.y.y.y/32
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hello
            port:
              number: 8080
#   host: hello.MYDOMAIN.ORG
