{{ if and .Values.global.addons.certmanager.enabled .Values.certmanager.clusterIssuers -}}
#
#  ClusterResourceSet: addconfiguration in workload cluster
#
---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    note: generated
  labels:
    type: generated
  name: {{ .Values.global.clusterName }}-cert-manager-issuers
  namespace: default
data:
  certmanagerIssuers: |
    {{- range .Values.certmanager.clusterIssuers }}
    ---
    {{- $enabled := printf "%t" .enabled }}
    {{- if regexMatch "nil" $enabled }}{{- $enabled = "true" }}{{- end }}
    {{- if (eq $enabled "true") }}
    apiVersion: cert-manager.io/v1
    kind: ClusterIssuer
    metadata:
      name: {{ .metadata.name }}
      namespace: cert-manager
    spec:
      {{- .spec | toYaml | nindent 6 }}
    {{- end }}
    {{- end }}
---
apiVersion: addons.cluster.x-k8s.io/v1beta1
kind: ClusterResourceSet
metadata:
  name: {{ .Values.global.clusterName }}-cert-manager-issuers
  namespace: default
spec:
  clusterSelector:
    matchLabels:
      certmanager.enabled: {{  printf "%t" .Values.global.addons.certmanager.enabled | quote }}
      certmanager.type: {{  .Values.global.addons.certmanager.type }}
      cluster.x-k8s.io/name: {{ .Values.global.clusterName }}
  resources:
  - kind: ConfigMap
    name: {{ .Values.global.clusterName }}-cert-manager-issuers
  strategy: Reconcile
{{ end -}}
