---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackCluster
metadata:
  name: {{ .Values.global.clusterName }}
  namespace: default
spec:
  bastion:
    enabled: {{ .Values.bastion.enabled | default "false" }}
    spec:
      flavor: {{ .Values.bastion.flavor }}
      image:
        filter:
          name: {{ .Values.bastion.image }}
      sshKeyName: {{ .Values.sshkeyname }}
  ## api with floating IP
  ## or externalnet enable is needed by bastion
  #disableExternalNetwork: false
  #externalNetwork:
  #  filter:
  #    name: FIP_EXT
  #apiServerFloatingIP: 100.67.66.91
  #
  ## api with internal IP
  disableExternalNetwork: true
  disableAPIServerFloatingIP: true
  apiServerFixedIP: {{ .Values.controlplane.apiServerFixedIP }}
  controlPlaneAvailabilityZones:
  {{- range .Values.controlplane.availabilityZones }}
  - {{ . }}
  {{- end }}
  router:
    filter:
      name: {{ .Values.router }}
  network:
    filter:
      {{- if .Values.network }}
      name: {{ .Values.network }}
      {{- end }}
  subnets:
    - filter:
        {{- if .Values.subnet }}
        name: {{ .Values.subnet }}
        {{- end }}
#  managedSubnets:
#  - cidr: 192.168.102.0/24
#    dnsNameservers:
#    - 192.168.2.10
#    allocationPools:
#      - start: 192.168.102.100
#        end: 192.168.102.252
  identityRef:
    cloudName: openstack
    name: {{ .Values.global.clusterName }}-cloud-config
  managedSecurityGroups:
    # DEBUG: security group inside cluster explicitly disabled
    allowAllInClusterTraffic: true
    allNodesSecurityGroupRules:
      - description: Created by cluster-api-provider-openstack - BGP (calico)
        direction: ingress
        etherType: IPv4
        name: BGP (Calico)
        portRangeMax: 179
        portRangeMin: 179
        protocol: tcp
        remoteManagedGroups:
          - controlplane
          - worker
      - description: Created by cluster-api-provider-openstack - IP-in-IP (calico)
        direction: ingress
        etherType: IPv4
        name: IP-in-IP (calico)
        protocol: "4"
        remoteManagedGroups:
          - controlplane
          - worker
