---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.clusterName }}-cloud-config
  labels:
    clusterctl.cluster.x-k8s.io/move: "true"
  annotations:
    #"helm.sh/resource-policy": "keep"
    ## install first, and delete at the end
    "helm.sh/hook": "pre-install,post-delete"
    "helm.sh/hook-weight": "-1"
    # For Argo, this resource should be pruned last out of everything
    argocd.argoproj.io/sync-options: PruneLast=true
data:
  cacert: {{ .Values.cloudConfig.cacert }}
  clouds.yaml: {{ .Values.cloudConfig.cloudsYaml }}
