{{- range $worker := .Values.workers }}
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: {{ $.Values.global.clusterName }}-{{ $worker.name }}
spec:
  clusterName: {{ $.Values.global.clusterName }}
  replicas: {{ $worker.replicas | default 0 }}
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: {{ $.Values.global.clusterName }}-{{ $worker.name }}
      clusterName: {{ $.Values.global.clusterName }}
      {{- if $worker.failureDomain }}
      failureDomain: {{ $worker.failureDomain }}
      {{- end }}
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: OpenStackMachineTemplate
        name: {{ $.Values.global.clusterName }}-{{ $worker.name }}-{{ $worker.version }}
      version: {{ $worker.version }}
---
{{- end }}
