---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackMachineTemplate
metadata:
  name: {{ .Values.global.clusterName }}-control-plane-{{ .Values.controlplane.version }}
  namespace: default
spec:
  template:
    spec:
      configDrive: true
    {{- with $.Values.controlplane.serverGroup }}
      serverGroup: {{- toYaml . | nindent 8 }}
    {{- end }}
      flavor: {{ .Values.controlplane.flavor }}
      image:
        filter:
          name: {{ .Values.controlplane.image }}
      sshKeyName: {{ .Values.sshkeyname }}
      ports:
        - network:
            filter:
              {{- if .Values.network }}
              name: {{ .Values.network }}
              {{- end }}
          fixedIPs:
            - subnet:
                filter:
                  {{- if .Values.subnet }}
                  name: {{ .Values.subnet }}
                  {{- end }}
          securityGroups:
            - filter:
                name: k8s-cluster-default-{{ .Values.global.clusterName }}-secgroup-controlplane
            - filter:
                name: allow-http
            - filter:
                name: allow-ssh
          allowedAddressPairs:
            - ipAddress: {{ .Values.controlplane.apiServerFixedIP }}
#          disablePortSecurity: true
#
      {{- if .Values.controlplane.rootVolume }}
      rootVolume:
        sizeGiB: {{ .Values.controlplane.rootVolume.sizeGiB }}
        type: {{ .Values.controlplane.rootVolume.type }}
      {{- end }}
#      additionalBlockDevices:
#        - name: etcd     ## Add etcd external volume
#          sizeGiB: 10
#          storage:
#            type: Volume
#            volume:
#              type: __DEFAULT__

