---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackMachineTemplate
metadata:
  name: {{ .Values.global.clusterName }}-control-plane-{{ .Values.controlplane.version }}
  namespace: default
spec:
  template:
    spec:
      configDrive: true
      serverGroup:
        filter:
          name: worker-node
      flavor: {{ .Values.controlplane.flavor }}
      image:
        filter:
          name: {{ .Values.controlplane.image }}
      sshKeyName: {{ .Values.sshkeyname }}
      ports:
        - network:
            filter:
              {{- if .Values.network }}
              name: {{ .Values.network }}
              {{- end }}
          fixedIPs:
            - subnet:
                filter:
                  {{- if .Values.subnet }}
                  name: {{ .Values.subnet }}
                  {{- end }}
          securityGroups:
            - filter:
                name: k8s-cluster-default-{{ .Values.global.clusterName }}-secgroup-controlplane
            - filter:
                name: allow-http
            - filter:
                name: allow-ssh
          allowedAddressPairs:
            - ipAddress: {{ .Values.controlplane.apiServerFixedIP }}
#          disablePortSecurity: true
#
#      rootVolume:
#        sizeGiB: 10
#        type: __DEFAULT__
#      additionalBlockDevices:
#        - name: etcd     ## Add etcd external volume
#          sizeGiB: 10
#          storage:
#            type: Volume
#            volume:
#              type: __DEFAULT__

