---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.clusterName }}-cloud-config
  labels:
    clusterctl.cluster.x-k8s.io/move: "true"
  annotations:
    #"helm.sh/resource-policy": "keep"
    "helm.sh/hook": pre-install,post-delete
data:
  cacert: {{ .Values.cloudConfig.cacert }}
  clouds.yaml: {{ .Values.cloudConfig.cloudsYaml }}
