{{ if and .Values.global.addons.cni.enabled ( eq .Values.global.addons.cni.type "cilium" ) -}}
apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: cni-cilium
spec:
  options:
    waitForJobs: true
    wait: true
    timeout: 30m0s
    install:
      createNamespace: true
  clusterSelector:
  # Target workload clusters with specific labels.
    matchLabels:
      cni.enabled: "true"
      cni.type: {{ .Values.global.addons.cni.type }}
      cni.version: {{ .Values.global.addons.cni.version }}
  # Target all workload clusters.
  #  matchLabels: {}
  releaseName: cilium
  repoURL: https://helm.cilium.io/
  chartName: cilium
  version: {{ .Values.global.addons.cni.version }}
  namespace: kube-system
  valuesTemplate: |
    {{- if .Values.dockerConfig.enabled }}
    imagePullSecrets:
     - name: regcred
    {{- end }}
    kubeProxyReplacement: true
    k8sServiceHost: {{`{{ .Cluster.spec.controlPlaneEndpoint.host }}`}}
    k8sServicePort: {{`{{ .Cluster.spec.controlPlaneEndpoint.port }}`}}
    hubble:
      relay:
        enabled: true
      ui:
        enabled: false
    ipam:
      mode: "cluster-pool"
      operator:
        clusterPoolIPv4PodCIDRList:{{`{{range $i, $cidr := .Cluster.spec.clusterNetwork.pods.cidrBlocks }}
          - "{{ $cidr }}"{{end}}`}}
        clusterPoolIPv4MaskSize: 24
    extraArgs:
      - "--mtu=1350"
    gatewayAPI:
      enabled: false
    # lb
    l2announcements:
      enabled: true
    externalIPs:
      enabled: true
    #
{{ end -}}
