{{ if .Values.global.addons.certmanager.enabled }}
apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: cert-manager
spec:
  clusterSelector:
    matchLabels:
      certmanager.enabled: "true"
      certmanager.type: {{ .Values.global.addons.certmanager.type }}
      certmanager.version: {{ .Values.global.addons.certmanager.version }}
  repoURL: https://charts.jetstack.io
  chartName: cert-manager
  namespace: cert-manager
  options:
    waitForJobs: true
    wait: true
    timeout: 30m0s
    install:
      createNamespace: true
  version: {{ .Values.global.addons.certmanager.version }}
  releaseName: cert-manager
  valuesTemplate: |
    fullnameOverride: cert-manager
    installCRDs: true
    extraEnv:
      {{- if .Values.global.http_proxy }}
      - name: http_proxy
        value: {{ .Values.global.http_proxy | quote }}
      {{- end }}
      {{- if .Values.global.https_proxy }}
      - name: https_proxy
        value: {{ .Values.global.https_proxy | quote }}
      {{- end }}
      {{- if .Values.global.no_proxy }}
      # exclude from proxy pods.cidrBlocks, services.cidrBlocks
      - name: no_proxy
        value: "{{ .Values.global.no_proxy }},{{`{{ ( index .Cluster.spec.clusterNetwork.pods.cidrBlocks 0 ) }}`}},{{`{{ (index .Cluster.spec.clusterNetwork.services.cidrBlocks 0 ) }}`}},.svc,.svc.cluster,.svc.cluster.local,127.0.0.0/8,16,192.168.0.0/16"
      {{- end }}
    resources:
      limits:
        memory: 100Mi
        cpu: 300m
      requests:
        memory: 100Mi
        cpu: 300m
    webhook:
      resources:
        limits:
          memory: 50Mi
          cpu: 10m
        requests:
          memory: 50Mi
          cpu: 10m
    cainjector:
      resources:
        limits:
          memory: 100Mi
          cpu: 10m
        requests:
          memory: 100Mi
          cpu: 10m
  # TODO: pay attention to newlines at the end that get inserted by templates
{{ end }}
