{{ if .Values.global.addons.storagelocal.enabled -}}
apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: local-path-provisioner
spec:
  options:
    waitForJobs: true
    wait: true
    timeout: 30m0s
    install:
      createNamespace: true
  clusterSelector:
    matchLabels:
      storagelocal.enabled: "true"
      storagelocal.type: {{ .Values.global.addons.storagelocal.type }}
      storagelocal.version: {{ .Values.global.addons.storagelocal.version }}
  repoURL: https://raw.githubusercontent.com/pli01/k8s-cluster-api-starter/main/openstack/deploy/helm-charts/repo/
  chartName: local-path-provisioner
  version: {{ .Values.global.addons.storagelocal.version }}
  releaseName: local-path-provisioner
  namespace: kube-system
  valuesTemplate: |
    tolerations:
      - key: "CriticalAddonsOnly"
        operator: "Exists"
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
    storageClass:
      defaultClass: true
      defaultVolumeType: local
      reclaimPolicy: Delete
      volumeBindingMode: WaitForFirstConsumer
    nodePathMap:
      - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
        paths:
          - /mnt/disk
    configmap:
      name: local-path-config
      setup: |-
        #!/bin/sh
        set -eu
        mkdir -m 0777 -p "${VOL_DIR}"
        chmod 700 "${VOL_DIR}/.."
      teardown: |-
        #!/bin/sh
        set -eu
        rm -rf "${VOL_DIR}"
      helperPod:
        namespaceOverride: ""
        name: "helper-pod"
        annotations: {}
{{ end -}}
