---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: capi-quickstart-md-0
  namespace: default
spec:
  template:
    spec:
      preKubeadmCommands:
        - echo TESTTESTTEST > /tmp/out
      postKubeadmCommands:
        - systemctl daemon-reload
        - systemctl restart containerd
      files:
        - path: /etc/apt/apt.conf.d/99proxy
          owner: "root:root"
          permissions: "0644"
          content: |
            Acquire {
              http::Proxy "http://192.168.2.10:8888";
              https::Proxy "http://192.168.2.10:8888";
              }
        - path: /etc/systemd/system/containerd.service.d/http-proxy.conf
          owner: "root:root"
          permissions: "0644"
          content: |
            [Service]
            Environment="HTTP_PROXY=http://192.168.2.10:8888"
            Environment="HTTPS_PROXY=http://192.168.2.10:8888"
            Environment="NO_PROXY=.svc,.svc.cluster,.svc.cluster.local,127.0.0.0/8,10.96.0.0/12,192.168.0.0/16"
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            cloud-provider: external
            provider-id: openstack:///'{{ instance_id }}'
          name: '{{ local_hostname }}'
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: capi-quickstart
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 172.16.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
    serviceDomain: cluster.local
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: capi-quickstart-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: OpenStackCluster
    name: capi-quickstart
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: capi-quickstart-md-0
  namespace: default
spec:
  clusterName: capi-quickstart
  replicas: 1
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: capi-quickstart-md-0
      clusterName: capi-quickstart
      failureDomain: AZ1
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: OpenStackMachineTemplate
        name: capi-quickstart-md-0
      version: v1.26.7
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: capi-quickstart-control-plane
  namespace: default
spec:
  kubeadmConfigSpec:
    preKubeadmCommands:
      - echo TESTTESTTEST > /tmp/out
    postKubeadmCommands:
      - systemctl daemon-reload
      - systemctl restart containerd
    files:
      - path: /etc/apt/apt.conf.d/99proxy
        owner: "root:root"
        permissions: "0644"
        content: |
          Acquire {
            http::Proxy "http://192.168.2.10:8888";
            https::Proxy "http://192.168.2.10:8888";
            }
      - path: /etc/systemd/system/containerd.service.d/http-proxy.conf
        owner: "root:root"
        permissions: "0644"
        content: |
          [Service]
          Environment="HTTP_PROXY=http://192.168.2.10:8888"
          Environment="HTTPS_PROXY=http://192.168.2.10:8888"
          Environment="NO_PROXY=.svc,.svc.cluster,.svc.cluster.local,127.0.0.0/8,10.96.0.0/12,192.168.0.0/16"
    clusterConfiguration:
      apiServer:
        extraArgs:
          cloud-provider: external
      controllerManager:
        extraArgs:
          cloud-provider: external
    initConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: external
          provider-id: openstack:///'{{ instance_id }}'
        name: '{{ local_hostname }}'
    joinConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: external
          provider-id: openstack:///'{{ instance_id }}'
        name: '{{ local_hostname }}'
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: OpenStackMachineTemplate
      name: capi-quickstart-control-plane
  replicas: 1
  version: v1.26.7
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackCluster
metadata:
  name: capi-quickstart
  namespace: default
spec:
  bastion:
    enabled: false
  #apiServerFloatingIP: 100.10.10.10
  disableAPIServerFloatingIP: true
  apiServerFixedIP: 192.168.2.100
  network:
    filter:
      name: network_services
  subnets:
    - filter:
        name: subnet_services
  router:
    filter:
      name: router_services
  disableExternalNetwork: true
#  externalNetwork:
#    filter:
#      name: _REPLACE_FIP_NETWORK_
  identityRef:
    cloudName: openstack
    name: capi-quickstart-cloud-config
  managedSecurityGroups:
    allowAllInClusterTraffic: true
    allNodesSecurityGroupRules:
    - description: Created by cluster-api-provider-openstack - BGP (calico)
      direction: ingress
      etherType: IPv4
      name: BGP (Calico)
      portRangeMax: 179
      portRangeMin: 179
      protocol: tcp
      remoteManagedGroups:
      - controlplane
      - worker
    - description: Created by cluster-api-provider-openstack - IP-in-IP (calico)
      direction: ingress
      etherType: IPv4
      name: IP-in-IP (calico)
      protocol: "4"
      remoteManagedGroups:
      - controlplane
      - worker
#  managedSubnets:
#  - cidr: 192.168.4.0/24
#    dnsNameservers:
#    - 192.168.2.10
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackMachineTemplate
metadata:
  name: capi-quickstart-control-plane
  namespace: default
spec:
  template:
    spec:
      configDrive: true
      flavor: CO1.2
      image:
        filter:
          name: ubuntu-2204-kube-v1.26.7
      sshKeyName: _TO_BE_REPLACE_
      ports:
      - network:
          filter:
            name: network_services
        fixedIPs:
          - subnet:
              filter:
                name: subnet_services
            ipAddress: 192.168.2.100
#        securityGroups:
#          - filter:
#               name: allow-ssh
#      rootVolume:
#        sizeGiB: 50
#        type: __DEFAULT__
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackMachineTemplate
metadata:
  name: capi-quickstart-md-0
  namespace: default
spec:
  template:
    spec:
      configDrive: true
      flavor: CO1.2
      image:
        filter:
          name: ubuntu-2204-kube-v1.26.7
      sshKeyName: _TO_BE_REPLACE_
      ports:
      - network:
          filter:
            name: network_services
        fixedIPs:
          - subnet:
              filter:
                name: subnet_services
