{{ if and .Values.global.addons.csi.enabled ( eq .Values.global.addons.csi.type "osc-bsu-csi" )  .Values.csi.storageClass -}}
#
#  ClusterResourceSet: addconfiguration in workload cluster
#
---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    note: generated
  labels:
    type: generated
  name: {{ .Values.global.clusterName }}-storage-class
  namespace: default
data:
  storageClass: |
    {{- range .Values.csi.storageClass }}
    ---
    {{- $enabled := printf "%t" .enabled }}
    {{- if regexMatch "nil" $enabled }}{{- $enabled = "true" }}{{- end }}
    {{- if (eq $enabled "true") }}
    apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: {{ .metadata.name }}
    {{- if hasKey .metadata "annotations" }}
      annotations: {{ .metadata.annotations | toYaml | nindent 8 }}
    {{- end }}
    {{- .spec | toYaml | nindent 4 }}
    {{- end }}
    {{- end }}
---
apiVersion: addons.cluster.x-k8s.io/v1beta1
kind: ClusterResourceSet
metadata:
  name: {{ .Values.global.clusterName }}-storage-class
  namespace: default
spec:
  clusterSelector:
    matchLabels:
      csi.enabled: {{  printf "%t" .Values.global.addons.csi.enabled | quote }}
      csi.type: {{  .Values.global.addons.csi.type }}
      cluster.x-k8s.io/name: {{ .Values.global.clusterName }}
  resources:
  - kind: ConfigMap
    name: {{ .Values.global.clusterName }}-storage-class
  strategy: Reconcile
{{ end -}}
