---
{{ if .Values.dockerConfig -}}
#
#  ClusterResourceSet: addconfiguration in workload cluster
#
---
apiVersion: v1
kind: Secret
type: addons.cluster.x-k8s.io/resource-set
metadata:
  annotations:
    note: generated
  labels:
    type: generated
  name: {{ .Values.global.clusterName }}-docker-config
  namespace: default
stringData:
  dockerconfigjson: |-
    apiVersion: v1
    kind: Secret
    type: kubernetes.io/dockerconfigjson
    metadata:
      name: regcred
      namespace: kube-system
    stringData:
      .dockerconfigjson: >-
        {
          "auths": {
            "{{ .Values.dockerConfig.registry }}": {
              "auth": "{{ .Values.dockerConfig.auth }}"
            }
          }
        }
---
apiVersion: addons.cluster.x-k8s.io/v1beta1
kind: ClusterResourceSet
metadata:
  name: {{ .Values.global.clusterName }}-docker-config
  namespace: default
spec:
  clusterSelector:
    matchLabels:
      cluster.x-k8s.io/name: {{ .Values.global.clusterName }}
  resources:
  - kind: Secret
    name: {{ .Values.global.clusterName }}-docker-config
  strategy: Reconcile
{{ end -}}
