---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OscCluster
metadata:
  name: {{ .Values.global.clusterName }}
spec:
  network:
    clusterName: {{ .Values.global.clusterName }}
    bastion:
      enable: {{ .Values.bastion.enable | default "false" }}
      clusterName: {{ .Values.global.clusterName }}
    internetService:
      clusterName: {{ .Values.global.clusterName }}
    loadBalancer:
      clusterName: {{ .Values.global.clusterName }}
      healthCheck:
        checkinterval: 5
        healthythreshold: 5
        port: 6443
        protocol: TCP
        timeout: 5
        unhealthythreshold: 2
      listener:
        backendport: 6443
        backendprotocol: TCP
        loadbalancerport: 6443
        loadbalancerprotocol: TCP
      loadbalancername: {{ .Values.loadbalancername | default "{{ .Values.global.clusterName }}-k8s" }}
      loadbalancertype: internet-facing
    natService:
      clusterName: {{ .Values.global.clusterName }}
    net:
      clusterName: {{ .Values.global.clusterName }}
    securityGroups:
    - description: Security Group Kw with {{ .Values.global.clusterName }}
      name: {{ .Values.global.clusterName }}-securitygroup-kw
      securityGroupRules:
      - name: {{ .Values.global.clusterName }}-securitygrouprule-kw-bgp
        flow: Inbound
        fromPortRange: 179
        toPortRange: 179
        ipProtocol: tcp
        ipRange: 10.0.0.0/16
      - name: {{ .Values.global.clusterName }}-securitygrouprule-api-kubelet-kw
        flow: Inbound
        fromPortRange: 10250
        toPortRange: 10250
        ipProtocol: tcp
        ipRange: 10.0.3.0/24
      - name: {{ .Values.global.clusterName }}-securitygrouprule-kw-nodeip-kcp
        flow: Inbound
        toPortRange: 32767
        fromPortRange: 30000
        ipProtocol: tcp
        ipRange: 10.0.4.0/24
      - name: {{ .Values.global.clusterName }}-securitygrouprule-api-kubelet-kcp
        flow: Inbound
        fromPortRange: 10250
        toPortRange: 10250
        ipProtocol: tcp
        ipRange: 10.0.4.0/24
      - name: {{ .Values.global.clusterName }}-securitygrouprule-kw-nodeip-kw
        flow: Inbound
        fromPortRange: 30000
        toPortRange: 32767
        ipProtocol: tcp
        ipRange: 10.0.3.0/24
    - description: Security Group Kcp with {{ .Values.global.clusterName }}
      name: {{ .Values.global.clusterName }}-securitygroup-kcp
      securityGroupRules:
      - name: {{ .Values.global.clusterName }}-securitygrouprule-kcp-bgp
        flow: Inbound
        fromPortRange: 179
        toPortRange: 179
        ipProtocol: tcp
        ipRange: 10.0.0.0/16
      - name: {{ .Values.global.clusterName }}-securitygrouprule-api-kw
        flow: Inbound
        fromPortRange: 6443
        toPortRange: 6443
        ipProtocol: tcp
        ipRange: 10.0.3.0/24
      - name: {{ .Values.global.clusterName }}-securitygrouprule-api-kcp
        flow: Inbound
        fromPortRange: 6443
        toPortRange: 6443
        ipProtocol: tcp
        ipRange: 10.0.4.0/24
      - name: {{ .Values.global.clusterName }}-securitygrouprule-kcp-nodeip-kw
        flow: Inbound
        fromPortRange: 30000
        toPortRange: 32767
        ipProtocol: tcp
        ipRange: 10.0.3.0/24
      - name: {{ .Values.global.clusterName }}-securitygrouprule-etcd
        flow: Inbound
        fromPortRange: 2379
        toPortRange: 2380
        ipProtocol: tcp
        ipRange: 10.0.4.0/24
      - name: {{ .Values.global.clusterName }}-securitygrouprule-kubelet-kcp
        flow: Inbound
        fromPortRange: 10250
        toPortRange: 10252
        ipProtocol: tcp
        ipRange: 10.0.4.0/24
      - name: {{ .Values.global.clusterName }}-securitugrouprule-kcp-nodeip-kcp
        flow: Inbound
        fromPortRange: 30000
        toPortRange: 32767
        ipProtocol: tcp
        ipRange: 10.0.4.0/24
    - description: Security Group Lb with {{ .Values.global.clusterName }}
      name: {{ .Values.global.clusterName }}-securitygroup-lb
      securityGroupRules:
      - name: {{ .Values.global.clusterName }}-securitygrouprule-lb
        flow: Inbound
        fromPortRange: 6443
        toPortRange: 6443
        ipProtocol: tcp
        ipRange: 0.0.0.0/0
    - description: Security Group Node with {{ .Values.global.clusterName }}
      name: {{ .Values.global.clusterName }}-securitygroup-node
      securityGroupRules:
      - name: {{ .Values.global.clusterName }}-securitygroup-calico-vxlan
        flow: Inbound
        fromPortRange: 4789
        toPortRange: 4789
        ipProtocol: udp
        ipRange: 10.0.0.0/16
      - name: {{ .Values.global.clusterName }}-securitygroup-typha
        flow: Inbound
        fromPortRange: 5473
        toPortRange: 5473
        ipProtocol: udp
        ipRange: 10.0.0.0/16
      - name: {{ .Values.global.clusterName }}-securitygroup-wireguard
        flow: Inbound
        fromPortRange: 51820
        toPortRange: 51820
        ipProtocol: udp
        ipRange: 10.0.0.0/16
      - name: {{ .Values.global.clusterName }}-securitygroup-wireguard-ipv6
        flow: Inbound
        fromPortRange: 51821
        toPortRange: 51821
        ipProtocol: udp
        ipRange: 10.0.0.0/16
      - name: {{ .Values.global.clusterName }}-securitygroup-flannel
        flow: Inbound
        fromPortRange: 4789
        toPortRange: 4789
        ipProtocol: udp
        ipRange: 10.0.0.0/16
      - name: {{ .Values.global.clusterName }}-securitygroup-flannel-udp
        flow: Inbound
        fromPortRange: 8285
        toPortRange: 8285
        ipProtocol: udp
        ipRange: 10.0.0.0/16
      # icmp
      - name: {{ .Values.global.clusterName }}-securitygroup-icmp
        flow: Inbound
        fromPortRange: 8
        toPortRange: 8
        ipProtocol: icmp
        ipRange: 10.0.0.0/16
      # cilium
      - name: {{ .Values.global.clusterName }}-securitygroup-cilium-vxlan
        flow: Inbound
        fromPortRange: 8472
        toPortRange: 8472
        ipProtocol: udp
        ipRange: 10.0.0.0/16
      - name: {{ .Values.global.clusterName }}-securitygroup-cilium-health
        flow: Inbound
        fromPortRange: 4240
        toPortRange: 4240
        ipProtocol: tcp
        ipRange: 10.0.0.0/16
      - name: {{ .Values.global.clusterName }}-securitygroup-cilium-hubble
        flow: Inbound
        fromPortRange: 4244
        toPortRange: 4244
        ipProtocol: tcp
        ipRange: 10.0.0.0/16
      tag: OscK8sMainSG
    subnets:
    - ipSubnetRange: 10.0.4.0/24
      name: {{ .Values.global.clusterName }}-subnet-kcp
      subregionName: {{ .Values.subregionName  }}
    - ipSubnetRange: 10.0.3.0/24
      name: {{ .Values.global.clusterName }}-subnet-kw
      subregionName: {{ .Values.subregionName  }}
    - ipSubnetRange: 10.0.2.0/24
      name: {{ .Values.global.clusterName }}-subnet-public
      subregionName: {{ .Values.subregionName  }}
