---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OscCluster
metadata:
  name: {{ .Values.global.clusterName }}
spec:
  network:
    clusterName: {{ .Values.global.clusterName }}
    bastion:
      enable: {{ .Values.bastion.enable | default "false" }}
      clusterName: {{ .Values.global.clusterName }}
    internetService:
      clusterName: {{ .Values.global.clusterName }}
    loadBalancer:
      clusterName: {{ .Values.global.clusterName }}
      healthCheck:
        checkinterval: 5
        healthythreshold: 5
        port: 6443
        protocol: TCP
        timeout: 5
        unhealthythreshold: 2
      listener:
        backendport: 6443
        backendprotocol: TCP
        loadbalancerport: 6443
        loadbalancerprotocol: TCP
      loadbalancername: {{ .Values.loadbalancername | default "{{ .Values.global.clusterName }}-k8s" }}
      loadbalancertype: internet-facing
    natService:
      clusterName: {{ .Values.global.clusterName }}
    net:
      clusterName: {{ .Values.global.clusterName }}
    securityGroups:
    - description: Security Group Kw with {{ .Values.global.clusterName }}
      name: {{ .Values.global.clusterName }}-securitygroup-kw
      securityGroupRules:
      - flow: Inbound
        fromPortRange: 179
        ipProtocol: tcp
        ipRange: 10.0.0.0/16
        name: {{ .Values.global.clusterName }}-securitygrouprule-kw-bgp
        toPortRange: 179
      - flow: Inbound
        fromPortRange: 10250
        ipProtocol: tcp
        ipRange: 10.0.3.0/24
        name: {{ .Values.global.clusterName }}-securitygrouprule-api-kubelet-kw
        toPortRange: 10250
      - flow: Inbound
        fromPortRange: 30000
        ipProtocol: tcp
        ipRange: 10.0.4.0/24
        name: {{ .Values.global.clusterName }}-securitygrouprule-kw-nodeip-kcp
        toPortRange: 32767
      - flow: Inbound
        fromPortRange: 10250
        ipProtocol: tcp
        ipRange: 10.0.4.0/24
        name: {{ .Values.global.clusterName }}-securitygrouprule-api-kubelet-kcp
        toPortRange: 10250
      - flow: Inbound
        fromPortRange: 30000
        ipProtocol: tcp
        ipRange: 10.0.3.0/24
        name: {{ .Values.global.clusterName }}-securitygrouprule-kw-nodeip-kw
        toPortRange: 32767
    - description: Security Group Kcp with {{ .Values.global.clusterName }}
      name: {{ .Values.global.clusterName }}-securitygroup-kcp
      securityGroupRules:
      - flow: Inbound
        fromPortRange: 179
        ipProtocol: tcp
        ipRange: 10.0.0.0/16
        name: {{ .Values.global.clusterName }}-securitygrouprule-kcp-bgp
        toPortRange: 179
      - flow: Inbound
        fromPortRange: 6443
        ipProtocol: tcp
        ipRange: 10.0.3.0/24
        name: {{ .Values.global.clusterName }}-securitygrouprule-api-kw
        toPortRange: 6443
      - flow: Inbound
        fromPortRange: 6443
        ipProtocol: tcp
        ipRange: 10.0.4.0/24
        name: {{ .Values.global.clusterName }}-securitygrouprule-api-kcp
        toPortRange: 6443
      - flow: Inbound
        fromPortRange: 30000
        ipProtocol: tcp
        ipRange: 10.0.3.0/24
        name: {{ .Values.global.clusterName }}-securitygrouprule-kcp-nodeip-kw
        toPortRange: 32767
      - flow: Inbound
        fromPortRange: 2378
        ipProtocol: tcp
        ipRange: 10.0.4.0/24
        name: {{ .Values.global.clusterName }}-securitygrouprule-etcd
        toPortRange: 2379
      - flow: Inbound
        fromPortRange: 10250
        ipProtocol: tcp
        ipRange: 10.0.4.0/24
        name: {{ .Values.global.clusterName }}-securitygrouprule-kubelet-kcp
        toPortRange: 10252
      - flow: Inbound
        fromPortRange: 30000
        ipProtocol: tcp
        ipRange: 10.0.4.0/24
        name: {{ .Values.global.clusterName }}-securitugrouprule-kcp-nodeip-kcp
        toPortRange: 32767
    - description: Security Group Lb with {{ .Values.global.clusterName }}
      name: {{ .Values.global.clusterName }}-securitygroup-lb
      securityGroupRules:
      - flow: Inbound
        fromPortRange: 6443
        ipProtocol: tcp
        ipRange: 0.0.0.0/0
        name: {{ .Values.global.clusterName }}-securitygrouprule-lb
        toPortRange: 6443
    - description: Security Group Node with {{ .Values.global.clusterName }}
      name: {{ .Values.global.clusterName }}-securitygroup-node
      securityGroupRules:
      - flow: Inbound
        fromPortRange: 4789
        ipProtocol: udp
        ipRange: 10.0.0.0/16
        name: {{ .Values.global.clusterName }}-securitygroup-calico-vxlan
        toPortRange: 4789
      - flow: Inbound
        fromPortRange: 5473
        ipProtocol: udp
        ipRange: 10.0.0.0/16
        name: {{ .Values.global.clusterName }}-securitygroup-typha
        toPortRange: 5473
      - flow: Inbound
        fromPortRange: 51820
        ipProtocol: udp
        ipRange: 10.0.0.0/16
        name: {{ .Values.global.clusterName }}-securitygroup-wireguard
        toPortRange: 51820
      - flow: Inbound
        fromPortRange: 51821
        ipProtocol: udp
        ipRange: 10.0.0.0/16
        name: {{ .Values.global.clusterName }}-securitygroup-wireguard-ipv6
        toPortRange: 51821
      - flow: Inbound
        fromPortRange: 4789
        ipProtocol: udp
        ipRange: 10.0.0.0/16
        name: {{ .Values.global.clusterName }}-securitygroup-flannel
        toPortRange: 4789
      - flow: Inbound
        fromPortRange: 8285
        ipProtocol: udp
        ipRange: 10.0.0.0/16
        name: {{ .Values.global.clusterName }}-securitygroup-flannel-udp
        toPortRange: 8285
      # cilium
      - flow: Inbound
        fromPortRange: 8472
        ipProtocol: udp
        ipRange: 10.0.0.0/16
        name: {{ .Values.global.clusterName }}-securityrgroup-cilium-vxlan
        toPortRange: 8472
      - flow: Inbound
        fromPortRange: 4240
        ipProtocol: tcp
        ipRange: 10.0.0.0/16
        name: {{ .Values.global.clusterName }}-securityrgroup-cilium-health
        toPortRange: 4240
      - flow: Inbound
        fromPortRange: 4244
        ipProtocol: tcp
        ipRange: 10.0.0.0/16
        name: {{ .Values.global.clusterName }}-securityrgroup-cilium-hubble
        toPortRange: 4244
      tag: OscK8sMainSG
#    subnets:
#    - ipSubnetRange: 10.0.4.0/24
#      name: {{ .Values.global.clusterName }}-subnet-kcp
#      subregionName: {{ .Values.subregionName  }}
#    - ipSubnetRange: 10.0.3.0/24
#      name: {{ .Values.global.clusterName }}-subnet-kw
#      subregionName: {{ .Values.subregionName  }}
#    - ipSubnetRange: 10.0.2.0/24
#      name: {{ .Values.global.clusterName }}-subnet-public
#      subregionName: {{ .Values.subregionName  }}
