apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OscMachineTemplate
metadata:
  name: {{ .Values.global.clusterName }}-control-plane-{{ .Values.controlplane.version }}
spec:
  template:
    spec:
      node:
        clusterName: {{ .Values.global.clusterName }}
        image:
          name: {{ .Values.controlplane.image }}
        keypair:
          name: {{ .Values.sshkeyname }}
          deleteKeypair: false
        vm:
          clusterName: {{ .Values.global.clusterName }}
          keypairName: {{ .Values.sshkeyname }}
          loadBalancerName: {{ .Values.global.clusterName }}-k8s
          role: controlplane
          rootDisk:
            rootDiskIops: 100
            rootDiskSize: 30
            rootDiskType: standard
          vmType: {{ .Values.controlplane.vmType }}
