{{- $values := .Values }}
{{- range $name, $pool := .Values.workers }}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OscMachineTemplate
metadata:
  name: {{ $.Values.global.clusterName }}-{{ $name }}-{{ $pool.version }}
spec:
  template:
    spec:
      node:
        clusterName: {{ $.Values.global.clusterName }}
        image:
          name: {{ $pool.image }}
        keypair:
          name: {{ $.Values.sshkeyname }}
          deleteKeypair: false
        vm:
          clusterName: {{ $.Values.global.clusterName }}
          keypairName: {{ $.Values.sshkeyname }}
          rootDisk:
            rootDiskIops: 100
            rootDiskSize: 30
            rootDiskType: standard
          vmType: {{ $pool.vmType }}
---
{{- end }}
